### ISSUE TITLE
Remove upper constraint on base version

### ISSUE THREAD

**Issue by jdwolk** [hlian/linklater#4]
Hi there!

:pray: Apologies if there are any glaring inconsistencies or outright falsehoods with the content below as I'm a relative beginner to Haskell.

I'm trying to use linklater with [stack](https://github.com/commercialhaskell/stack) and [stackage](https://www.stackage.org). The earliest LTS version of Haskell I can find through Stackage is 1.0, which supports `base-4.7.0.2`.

`stack build` is failing due to the following:

```
--  Failure when adding dependencies:
      base: needed (<=4.7.0.1), but 4.7.0.2 found
    needed for package: linklater-3.1.0.0
```

Is there any particular reason why there is an upper version restriction on `base`?

Let me know if I can provide any more info. Would be really great if I could use `linklater` with stack!

**Comment by hlian** [comment]
@jdwolk I'm on it!

**Comment by hlian** [comment]
@jdwolk Uploaded 3.2.0.0 to Hackage. Should work now. Give it a try.
