### ISSUE TITLE
Versioning discrepancy?

### ISSUE THREAD

**Issue by apolishch** [hlian/linklater#6]
The latest version available on cabal (or documented) is 3.2.0.0, however the linklater.cabal file refers to itself as 4.0.0.0. Is a new version in the works?

**Comment by hlian** [comment]
@apolishch yes! hopefully things are more clear now with the README. let me give you write access so you can fix things as you see them

**Comment by tshelburne** [comment]
What is still remaining to bump this and release a newer version? The discrepancies are actually pretty confusing, and it's not clear what is left. Took quite some time to figure out what the actual state of things is.

**Comment by hlian** [comment]
@apolishch @tshelburne released 4.0.0 to hackage today, hope that helps

**Comment by tshelburne** [comment]
Thanks man, appreciated.
