### ISSUE TITLE
Variable not in scope: checkResponse

### ISSUE THREAD

**Issue by elizabethsiegle** [hlian/linklater#8]
When I _cabal install twilio_ using this [library](https://github.com/markandrus/twilio-haskell), I get the following error:

![image](https://user-images.githubusercontent.com/8932430/27359879-0a73e832-55d3-11e7-8532-50f8bd738dff.png)

**Comment by hlian** [comment]
linklater can't be cabal installed correctly since it's missing version bounds! it's meant to be stack installed instead :/
