### ISSUE TITLE
Trouble using 'say' function

### ISSUE THREAD

**Issue by ggranberry** [hlian/linklater#9]
http://lpaste.net/360345

While writing a small slackbot using linklater I noticed that providing a Message and Config object to 'say' returned a value that violates functional dependencies. Can anyone provide any insights into what I'm doing wrong here?

**Comment by hlian** [comment]
@ggranberry try this!

```haskell
(False,  m) -> do
  anEither <- say m config
  case anEither of
    Left e -> putStrLn ("an error occurred! " <> show e)
    Right _ -> return ""
```

**Comment by hlian** [comment]
@ggranberry silly me! i was missing a `runExceptT` call. i updated JPEGbot to illustrate the solution:

https://github.com/hlian/linklater/blob/master/examples/app/JointPhotographicExpertsGroupTonga.hs#L62

**Comment by ggranberry** [comment]
@hlian That did the trick, thanks!!
